name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v4

    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: 'Install packages'
      working-directory: forever_rss/web
      run: yarn install
  
    - name: 'Run unit-tests'
      working-directory: forever_rss/web
      run: yarn test
