name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      working-directory: forever_rss/web
      run: yarn install
  
    - name: Run unit-tests
      working-directory: forever_rss/web
      run: yarn test

    - name: Build server docker image
      run: docker build -t fr .

    - name: Configure AWS credentials
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Tag image for main and push to ECR
      if: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]'  }}
      run: |
        docker tag fr ${{ secrets.AWS_ECR_ENDPOINT }}:main-${GITHUB_SHA::8}
        docker tag fr ${{ secrets.AWS_ECR_ENDPOINT }}:main-latest
        docker push ${{ secrets.AWS_ECR_ENDPOINT }}:main-${GITHUB_SHA::8}
        docker push ${{ secrets.AWS_ECR_ENDPOINT }}:main-latest
